# Generated by Django 5.0.2 on 2024-02-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_id', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=64)),
                ('latitude', models.FloatField(max_length=64)),
                ('longitude', models.FloatField(max_length=64)),
            ],
        ),
    ]
