# Generated by Django 5.0.2 on 2024-02-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0002_alter_bookshelf_shelf_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='shelf_id',
        ),
    ]
